{
 "title": "Реклама",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Заработок по дням",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(spent) as count_impressions, date FROM ad_impressions GROUP BY date ORDER BY date"
    },
    {
     "rawSql": "SELECT SUM(spent) AS count_clicks, date FROM ad_clicks GROUP BY date ORDER BY date"
    }
   ]
  },
  {
   "title": "Количество просмотров и кликов по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(spent) as count_impressions, date FROM ad_impressions GROUP BY date ORDER BY date"
    },
    {
     "rawSql": "SELECT COUNT(spent) AS count_clicks, date FROM ad_clicks GROUP BY date ORDER BY date"
    }
   ]
  },
  {
   "title": "Конверсия по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(spent) impressions, date FROM ad_impressions GROUP BY date ORDER BY date"
    },
    {
     "rawSql": "SELECT COUNT(spent) clicks, date FROM ad_clicks GROUP BY date ORDER BY date"
    }
   ]
  },
  {
   "title": "Доходы в зависимости от пола",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(spent) views, cl.gender FROM ad_impressions JOIN clients cl ON ad_impressions.client_id = cl.id GROUP BY cl.gender"
    },
    {
     "rawSql": "SELECT SUM(spent) clicks, cl.gender FROM ad_clicks JOIN clients cl ON ad_clicks.client_id = cl.id GROUP BY cl.gender"
    }
   ]
  },
  {
   "title": "Доходы в зависимости от локации",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(spent) views, cl.location FROM ad_impressions JOIN clients cl ON ad_impressions.client_id = cl.id GROUP BY cl.location"
    },
    {
     "rawSql": "SELECT SUM(spent) clicks, cl.location FROM ad_clicks JOIN clients cl ON ad_clicks.client_id = cl.id GROUP BY cl.location"
    }
   ]
  },
  {
   "title": "Доходы в зависимости от возраста",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(spent) views, cl.age FROM ad_impressions JOIN clients cl ON ad_impressions.client_id = cl.id GROUP BY cl.age"
    },
    {
     "rawSql": "SELECT SUM(spent) clicks, cl.age FROM ad_clicks JOIN clients cl ON ad_clicks.client_id = cl.id GROUP BY cl.age"
    },
    {
     "rawSql": "SELECT COUNT(spent) views_cnt, cl.age FROM ad_impressions JOIN clients cl ON ad_impressions.client_id = cl.id GROUP BY cl.age"
    }
   ]
  }
 ]
}